name: CD to EKS

on:
  workflow_dispatch:  # Manual trigger via GitHub Actions UI

jobs:
  deploy:
    name: Manually Deploy to EKS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Update kubeconfig for EKS Cluster
      run: |
        aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

    - name: Create zomato namespace (if not exists)
      run: |
        kubectl get namespace zomato || kubectl create namespace zomato

    - name: Deploy to EKS using kubectl in zomato namespace
      run: |
        kubectl apply -f Kubernetes/deployment.yaml --namespace=zomato
        kubectl apply -f Kubernetes/service.yaml --namespace=zomato
